bucket_name            = ""
cors_allowed_headers   = [""]
cors_allowed_methods   = [""]
cors_allowed_origins   = [""]
cors_max_age_seconds   = 
region                 = ""
versioning             = 
website_index_document = ""
website_error_document = ""